Repository truenas/apps_validation, pull requests merged in 2024-07, with the labels that each got.

#26 NAS-129729 / 24.10 / Properly check if version has been bumped for an app
  apps_ci/scripts/catalog_update.py
Labels: skip jira status

#28 NAS-129962 / 24.10 / Include version key when retrieving app details
  catalog_reader/app.py
Labels: jira

#29 NAS-129989 / 24.10 / Change ix volume and acl features to not use camel case
  apps_schema/features/ix_volume.py
  catalog_reader/questions.py
  catalog_reader/questions_util.py
Labels: jira

#31 NAS-130046 / 24.10 / Fix apps schema features casing
  apps_schema/features/basic.py
  apps_schema/features/certificate.py
  apps_schema/features/container_image.py
  apps_schema/features/interface.py
  apps_schema/features/node.py
Labels: jira

#32 NAS-130074 / 24.10 / Fix certificate authority ref
  catalog_reader/questions.py
Labels: jira

#33 NAS-130170 / 24.10 / Fix node_ip feature
  apps_schema/features/node.py
  catalog_reader/app_utils.py
  catalog_reader/questions.py
Labels: jira

#35 NAS-130172 / 24.10 / Validate specified portals and notes
  apps_validation/portals.py
  apps_validation/validate_templates.py
Labels: jira, skip jira status

#34 NAS-130171 / 24.10 / Allow force flag for ACLs being applied on ix volumes
  catalog_reader/questions_util.py
Labels: jira

#38 NAS-130323 / 24.10 / Make sure ix_values.yaml file is provided to compose rendering if it exists
  catalog_templating/scripts/render_compose.py
Labels: jira
